CREATE TABLE wine
(
    code bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content integer NOT NULL,
    harvest integer NOT NULL,
    name character varying(255) NOT NULL,
    price numeric(19,2) NOT NULL,
    type character varying(255) NOT NULL
)